import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Header from '@/components/header';

const font = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn('dark', font.className)}>
        <Header />
        {children}
        <footer>
          <div className="container py-4">
            <p className="text-sm text-center text-muted">
              &copy;2023. Designed by Rehx
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
